### ISSUE TITLE
所以自定表情包设置成功后要怎么才会让他发？

### ISSUE THREAD

**Issue by fsqhn** [DMCSWCG/nonebot-plugin-customemote#5]
试了好多都没发
![QQ截图20230321180232](https://user-images.githubusercontent.com/13745793/226573683-0ab1fbef-422e-48af-9a8f-9ff2ba6c0237.png)

**Comment by DMCSWCG** [comment]
hi，设置时请不要带上.jpg的后缀。只输入表情需要设置的名字

**Comment by fsqhn** [comment]
大概懂了，试了下能用了，非常感谢解答。
